controller_list:
  - name: fake_abb_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_mobile_bot_controller
    joints:
      - left_back_wheel_joint
      - left_front_wheel_joint
      - right_back_wheel_joint
      - right_front_wheel_joint
initial:  # Define initial robot poses.
  - group: abb_arm
    pose: home
  - group: mobile_bot
    pose: mobile_base